check if dir exists

diff --git a/workflow.yml b/workflow.yml
--- a/workflow.yml
+++ b/workflow.yml
@@ -9,6 +9,20 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+
+    - name: Check if remote folder exists
+      continue-on-error: false
+      uses: appleboy/ssh-action@v0.1.6
+      with:
+        host: ${{ vars.SSH_HOST }}
+        username: ${{ vars.SSH_USER }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        script: |
+          if [ ! -d "${{ vars.SSH_PATH }}" ]; then
+            echo "Error: Remote Directory ${{ vars.SSH_PATH }} does not exist!" >&2
+            exit 1
+          fi
+
     - name: Checkout Code
       uses: actions/checkout@v3
 
@@ -39,8 +53,13 @@ jobs:
         username: ${{ vars.SSH_USER }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
-          cd ${{ vars.SSH_PATH }}
-          find . -mindepth 1 ! -path './storage/*' ! -name '.env' ! -name 'storage' -exec rm -rf {} +
+          if [ -d "${{ vars.SSH_PATH }}" ]; then
+            cd ${{ vars.SSH_PATH }}
+            find . -mindepth 1 ! -path './storage/*' ! -name '.env' ! -name 'storage' -exec rm -rf {} +
+          else
+            echo "Error: Directory ${{ vars.SSH_PATH }} does not exist!" >&2
+            exit 1
+          fi
 
     - name: Synchronize Files To Server
       uses: easingthemes/ssh-deploy@v2.1.5
